sudo: required
services:
  - docker

before_install:
  - docker build -t pranayreddocker/docker-react -f Dockerfile.dev . 

script:
  - docker run pranayreddocker/docker-react npm run test -- --coverage