version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    
    environment: 
      - CHOKIDAR_USEPOLLING=true
    
    ports:
      - "2001:3000"
    volumes: 
      - /app/node_modules
      - .:/app